name: Crescent table pipeline

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        repository: percyqaz/Percyqaz.Common
        path: Percyqaz.Common
        
    - uses: actions/checkout@v3
      with:
        repository: YAVSRG/Prelude
        path: Prelude
        
    - uses: actions/checkout@v3
      with:
        path: Backbeat
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        
    - name: Commit table changes via tool
      run: cd Backbeat/tools && dotnet run -- commit crescent
      
    - name: Read changelog contents
      id: read_file
      uses: andstor/file-reader-action@v1
      with:
        path: "Backbeat/tables/crescent.diff"
        
    - name: Post changes to webhook
      uses: tsickert/discord-webhook@v5.3.0
      if: ${{ steps.read_file.outputs.contents != '' }}
      with:
        webhook-url: ${{ secrets.CONTENT_WEBHOOK_URL }}
        content: ${{ steps.read_file.outputs.contents }}
        
    - name: Commit changed files
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: <🌙> Apply pending table changes
        skip_checkout: true
        skip_fetch: true
